#!/usr/bin/env bash

set -euo pipefail

theme_keybinds='configuration {show-icons: false;} window {width: 300px;} inputbar {enabled: false;} element-text {vertical-align: 0.50; horizontal-align: 0.50;} mode-switcher {enabled: false;}'

theme_waybar='configuration {show-icons: false;} window {location: north west; x-offset: 4; y-offset: 2; width: 250px;} inputbar {enabled: false;} element-text {vertical-align: 0.50; horizontal-align: 0.50;} mode-switcher {enabled: false;}'

# Get list of sources and select one
sources=$(pactl list short sources | awk '{print $2}' | grep -v '.monitor$')
chosen=$(printf "%s\n" "${sources[@]}" | rofi -dmenu \
    -i \
    -l 5 \
    -p "Microphone:" \
    -theme-str "$theme_keybinds")

if [[ -n "$chosen" ]]; then
    pactl set-default-source "$chosen" && notify-send "Microphone switched to $chosen!"
else
    exit 0
fi

if [[ "${1:-}" == "waybar" ]]; then
    theme="$theme_waybar"
else
    theme="$theme_keybinds"
fi
