#!/usr/bin/env bash

set -euo pipefail
uptime="$(uptime -p | sed -e 's/up //g')"

theme_keybinds='configuration {show-icons: false;} window {width: 300px;} inputbar {enabled: false;} element-text {vertical-align: 0.50; horizontal-align: 0.50;} mode-switcher {enabled: false;}'

theme_waybar='configuration {show-icons: false;} window {location: north west; x-offset: 4; y-offset: 2; width: 250px;} inputbar {enabled: false;} element-text {vertical-align: 0.50; horizontal-align: 0.50;} mode-switcher {enabled: false;}'

# Get list of sinks and select one
sinks=$(pactl list short sinks | awk '{print $2}')
chosen=$(printf "%s\n" "${sinks[@]}" | rofi -dmenu \
    -i \
    -l 5 \
    -p "Output:" \
    -theme-str "$theme_keybinds")

if [[ -n "$chosen" ]]; then
    pactl set-default-sink "$chosen" && notify-send "Audio switched!"
else
    exit 0
fi

if [[ "${1:-}" == "waybar" ]]; then
    theme="$theme_waybar"
else
    theme="$theme_keybinds"
fi
