general {
    lock_cmd = /home/$USER/.config/hypr/Hyprlock_RandomBackgrounbd.sh
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 60
    on-timeout = brightnessctl -s set 1
    on-resume = brightnessctl -r
}


listener {
    timeout = 250
    on-timeout = /home/$USER/.config/hypr/Hyprlock_RandomBackgrounbd.sh
}

listener {
    timeout = 4500
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 86400
    on-timeout = shutdown
}
