fs=yes

volume=50
volume-max=150

#fixes the color problem within the laptop
# it could be the laptop scrn is hdr?
vo=gpu-next
target-colorspace-hint=auto
target-colorspace-hint-mode=source
hdr-compute-peak=no
