#!/bin/bash

# Source paths
paths=(
  # "/run/media/ahmed/drivec/Playstation_2_games/"
  # "/run/media/ahmed/drivec/PC_GAMES/"
  "$HOME/Games_non_steam/"
  "$HOME/.local/share/Steam/userdata/418183881/config/grid"
  "$HOME/.local/share/Steam/userdata/418183881/config/localconfig.vdf"
  "$HOME/.local/share/Steam/userdata/418183881/config/shortcuts.vdf"
  "$HOME/.config/dolphinrc"
  "$HOME/.local/share/kxmlgui5/dolphin/dolphinui.rc"
  "$HOME/.config/qt5ct/qt5ct.conf"
  "$HOME/.config/kdeglobals"
  "$HOME/.config/plasma-org.kde.plasma.desktop-appletsrc"
  "$HOME/.config/kwinrc"
  # "$HOME/.local/share/konsole/Garuda.profile"
  "$HOME/.config/konsolerc"
  "$HOME/.config/fish/config.fish"
  "$HOME/.config/fish/fish_variables"
  "$HOME/.config/autostart/"
  "$HOME/.config/gtk-3.0/settings.ini"
  "$HOME/.config/menus/applications.menu"
  "$HOME/.config/fish/config.fish"
  # "~/.config/syncthingtray.ini"
  "$HOME/.config/spectaclerc"
  "$HOME/.config/ksnip/ksnip.conf"
  "$HOME/.librewolf"
  "$HOME/.config/xdg-desktop-portal/hyprland-portals.conf"
  "$HOME/.bashrc"
  "/etc/default/grub"
  "$HOME/.config/mimeapps.list"
  "$HOME/homebrew"
  "$HOME/.config/steam-rom-manager/"
  "/etc/sddm.conf"
)

# Get additional paths from syncthing config
while IFS= read -r path; do
    paths+=("$path")
done < <(grep -o 'path="[^"]*"' $HOME/.local/state/syncthing/config.xml | sed 's/path="//g' | sed 's/"//g')

# Destination directory
backup_dir="$HOME/linkstobackuap"

# Create destination directory if it doesn't exist
mkdir -p "$backup_dir"

# Create symbolic links only if they don't exist
for path in "${paths[@]}"; do
    # Extract the base name (last component of the path)
    base_name=$(basename "$path")
    link_path="$backup_dir/$base_name"

    # Check if the link already exists
    if [[ ! -e "$link_path" ]]; then
        echo "Creating symlink: $link_path -> $path"
        ln -sf "$path" "$link_path"
    else
        echo "Symlink already exists: $link_path"
    fi
done
